# Étape 1 : Utiliser l'image de base Nginx
FROM nginx:latest

# Étape 2 : Copier la configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Étape 3 : Copier les fichiers statiques depuis l'image Django
COPY --from=gestion_paie-django /app/staticfiles /usr/share/nginx/html/static

# Étape 4 : Exposer le port 80
EXPOSE 80
