# Generated by Django 3.2.25 on 2024-11-19 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rib_Employe', models.CharField(max_length=1000, unique=True, validators=[django.core.validators.RegexValidator('^\\d{20}$')])),
                ('Fullname', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$')])),
                ('Address', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='FichierPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{2}$')])),
                ('type', models.CharField(choices=[('confraires', 'confraires'), ('BADR', 'BADR')], default='BADR', max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Montant', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('Libelle', models.CharField(blank=True, max_length=70, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$')])),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.employe')),
                ('fiche_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.fichierpaie')),
            ],
        ),
    ]
