# Generated by Django 3.2.25 on 2025-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpaie',
            name='type',
            field=models.CharField(choices=[('confraires_BADR', 'confraires_BADR'), ('BADR', 'BADR'), ('CPA', 'CPA'), ('confraires_CPA', 'confraires_CPA')], max_length=15),
        ),
    ]
