# Generated by Django 3.2.25 on 2025-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0002_alter_fichierpaie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpaie',
            name='type',
            field=models.CharField(choices=[('confraires_BADR', 'confraires_BADR'), ('BADR', 'BADR'), ('CPA', 'CPA')], max_length=15),
        ),
    ]
